# Generated by Django 5.2.14 on 2026-05-15 08:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_sessions', '0001_initial'),
        ('devices', '0001_initial'),
        ('projects', '0001_initial'),
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['owner', '-created_at'], name='task_owner_created_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['owner', 'status'], name='task_owner_status_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['device', 'status', 'created_at'], name='task_queue_idx'),
        ),
        migrations.AddIndex(
            model_name='taskevent',
            index=models.Index(fields=['task', 'sequence'], name='task_event_sequence_idx'),
        ),
    ]
