# Generated by Django 5.2.14 on 2026-05-15 10:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_sessions', '0001_initial'),
        ('devices', '0001_initial'),
        ('projects', '0002_project_default_approval_policy_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agentsession',
            options={'ordering': ['-last_activity_at', '-created_at']},
        ),
        migrations.AddField(
            model_name='agentsession',
            name='codex_session_id',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='agentsession',
            name='last_activity_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentsession',
            name='parent_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forks', to='agent_sessions.agentsession'),
        ),
        migrations.AddField(
            model_name='agentsession',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='agentsession',
            name='title',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddIndex(
            model_name='agentsession',
            index=models.Index(fields=['owner', 'project', 'status', '-updated_at'], name='session_owner_project_idx'),
        ),
        migrations.AddIndex(
            model_name='agentsession',
            index=models.Index(fields=['codex_session_id'], name='session_codex_id_idx'),
        ),
    ]
