# Generated by Django 5.2.14 on 2026-05-15 18:56

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_sessions', '0002_alter_agentsession_options_and_more'),
        ('tasks', '0002_task_task_owner_created_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentsession',
            name='approval_policy',
            field=models.CharField(default='on-request', max_length=40),
        ),
        migrations.AddField(
            model_name='agentsession',
            name='model',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='agentsession',
            name='profile',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='agentsession',
            name='sandbox',
            field=models.CharField(default='workspace-write', max_length=40),
        ),
        migrations.AddField(
            model_name='agentsession',
            name='selected_skills',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='agentsession',
            name='tool_settings',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='agentsession',
            name='web_search_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='SessionMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], max_length=20)),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('running', 'Running'), ('complete', 'Complete'), ('error', 'Error')], default='sent', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='agent_sessions.agentsession')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='tasks.task')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['session', 'created_at'], name='session_message_time_idx'), models.Index(fields=['task', 'role'], name='session_message_task_idx')],
            },
        ),
    ]
