# Generated by Django 5.2.14 on 2026-05-15 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='default_approval_policy',
            field=models.CharField(choices=[('untrusted', 'Untrusted'), ('on-request', 'On request'), ('never', 'Never')], default='on-request', max_length=40),
        ),
        migrations.AddField(
            model_name='project',
            name='default_model',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='project',
            name='default_profile',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='project',
            name='default_sandbox',
            field=models.CharField(choices=[('read-only', 'Read only'), ('workspace-write', 'Workspace write'), ('danger-full-access', 'Danger full access')], default='workspace-write', max_length=40),
        ),
    ]
