# Generated by Django 5.2.14 on 2026-05-15 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='capabilities',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='device',
            name='capabilities_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
